### ISSUE TITLE
Syntax error with glyphs that contain a %

### ISSUE THREAD

**Issue by LettError** [typemytype/GlyphConstruction#7]
Lines with a % symbol cause syntax errors.
'''Hbar = H + macron.cap@center,70%|0126'''
cause tracebacks. Commenting the line helps.

'''python
Traceback (most recent call last):
  File "lib/doodleDelegate.pyc", line 169, in sendEvent_
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/vanilla/vanillaBase.py", line 210, in action_
    self.callback(sender)
  File "glyphConstructionUI.py", line 683, in reload
    self.constructionsCallback(self.constructions, update)
  File "glyphConstructionUI.py", line 564, in constructionsCallback
    constructionGlyph = GlyphConstructionBuilder(construction, self.glyphConstructorFont)
  File "/Users/erik/Develop/svn.letterror.com/scripts/doodle/GlyphConstruction/glyphConstructionBuilder.py", line 695, in GlyphConstructionBuilder
    component, transformMatrix = parsePositions(baseMarkGlyph, markGlyph, font, markTransformMap, advanceWidth, advanceHeight)
  File "/Users/erik/Develop/svn.letterror.com/scripts/doodle/GlyphConstruction/glyphConstructionBuilder.py", line 479, in parsePositions
    markPoint2, markAngle2, markFixedY = parsePosition(markGlyph, font, positionY, direction="y", prefix="_")
  File "/Users/erik/Develop/svn.letterror.com/scripts/doodle/GlyphConstruction/glyphConstructionBuilder.py", line 379, in parsePosition
    exec("positionName=%s" % positionName)
  File "<string>", line 1
    positionName=70%
                   ^
SyntaxError: invalid syntax
'''

**Comment by typemytype** [comment]
you are using the latest?
should have been fixed here https://github.com/typemytype/GlyphConstruction/commit/8692d88765b1cadcb743be67f269b109e8e1b469

**Comment by LettError** [comment]
Ok, that was an old version. New version says:

```
Traceback (most recent call last):
  File "glyphConstructionUI.py", line 26, in <module>
  File "/Users/erik/Develop/svn.letterror.com/scripts/doodle/GlyphConstruction/glyphConstructionLexer.py", line 21, in <module>
AttributeError: 'module' object has no attribute 'flipMarkGlyphSplit'
Traceback (most recent call last):
  File "glyphConstructionUI.py", line 26, in <module>
  File "/Users/erik/Develop/svn.letterror.com/scripts/doodle/GlyphConstruction/RoboFont/glyphConstructionLexer.py", line 21, in <module>
AttributeError: 'module' object has no attribute 'flipMarkGlyphSplit'
```

**Comment by typemytype** [comment]
should be solved by import the builder before the lecture

https://github.com/typemytype/GlyphConstruction/commit/9b9d2481b85894e665eaa2b2281c951d0b50b493
