### ISSUE TITLE
Expression fails with `fontParts.fontshell.RFont` but works fine in RoboFont

### ISSUE THREAD

**Issue by roberto-arista** [typemytype/GlyphConstruction#74]
hey @typemytype!

I have encountered a weird bug. I have set a repo to easily reproduce it:
https://github.com/roberto-arista/glyphConstructionIssue

I often use in production `glyphConstruction` to build superiors and similar. Using expressions like:
```
a.superior = a.denominator@origin, origin+200
```

Yesterday I started to work on a new set of small number and I started to get TypeErrors like this one:
```
Traceback (most recent call last):
  File "/Users/robertoarista/Documents/Repositories/glyphConstructionIssue/issue.py", line 22, in <module>
    constructionGlyph = GlyphConstructionBuilder(eachConstruction, font)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robertoarista/Documents/Repositories/glyphConstructionIssue/.venv/lib/python3.11/site-packages/glyphConstruction.py", line 1185, in GlyphConstructionBuilder
    component, transformMatrix = parsePositions(baseMarkGlyph, markGlyph, font, markTransformMap, advanceWidth, advanceHeight)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robertoarista/Documents/Repositories/glyphConstructionIssue/.venv/lib/python3.11/site-packages/glyphConstruction.py", line 626, in parsePositions
    if baseGlyphX in font and baseGlyphY in font:
       ^^^^^^^^^^^^^^^^^^
  File "/Users/robertoarista/Documents/Repositories/glyphConstructionIssue/.venv/lib/python3.11/site-packages/fontParts/base/layer.py", line 169, in __contains__
    name = normalizers.normalizeGlyphName(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robertoarista/Documents/Repositories/glyphConstructionIssue/.venv/lib/python3.11/site-packages/fontParts/base/normalizers.py", line 303, in normalizeGlyphName
    raise TypeError("Glyph names must be strings, not %s."
TypeError: Glyph names must be strings, not NoneType.
```

A bit weird, since I was used to this kind of construction, I have used it already.
I tested a few other options, and basically the issue lies with 2 aspects:
- the anchoring (what follows the @), if you remove it, no exception
- the fact that is a single component. If you add `space +` after the equal sign it works fine (you can then correct the spacing with ^ at the end of the expression)

Another weird fact, both instructions:
https://github.com/roberto-arista/glyphConstructionIssue/blob/dc1061000f98059d6fb268eac241af1e616bd74f/issue.py#L9-L12

work just fine in RoboFont
<img width="1552" alt="Screenshot 2023-04-12 at 22 00 54" src="https://user-images.githubusercontent.com/2218712/231573485-6773cbbb-8308-4210-bdbe-60de8ea39fba.png">

Let me know if you need extra info.

**Comment by typemytype** [comment]
should be fixed...

**Comment by roberto-arista** [comment]
thanks, I'll check tomorrow!
