### ISSUE TITLE
Dash in glyph names confuses the margin math

### ISSUE THREAD

**Issue by typoman** [typemytype/GlyphConstruction#76]
It seems that if there is a dash in glyph names the math is not calculated correctly for the margins. Here is an example:

```
# this works
# >g2-tmp = ^ g1-tmp, g1-tmp

# math is not working correclty
>g2-tmp = ^ g1-tmp*1.25, g1-tmp/1.6
```

The parser apparently separates the glyph names even when there is no space between dash and a glyph name.

**Comment by typoman** [comment]
I tried to use explicit math and glyph name start and end indicators:

```
>g2-tmp = ^ "g1-tmp" `*1`, "g1-tmp" `/1`

# or

>g2-tmp = ^ "g1-tmp" * 1, "g1-tmp" / 1
```

 and I got this error:
```
Traceback (most recent call last):
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/vanilla/vanillaBase.py", line 520, in action_
  File "/Users/bman/Library/Application Support/RoboFont/plugins/GlyphConstruction.roboFontExt/lib/glyphConstructionController.py", line 805, in reload
  File "/Users/bman/Library/Application Support/RoboFont/plugins/GlyphConstruction.roboFontExt/lib/glyphConstructionController.py", line 647, in constructionsCallback
  File "/Users/bman/Library/Application Support/RoboFont/plugins/GlyphConstruction.roboFontExt/lib/glyphConstruction.py", line 1212, in GlyphConstructionBuilder
  File "/Users/bman/Library/Application Support/RoboFont/plugins/GlyphConstruction.roboFontExt/lib/glyphConstruction.py", line 200, in _set_leftMargin
TypeError: unsupported operand type(s) for -: 'str' and 'int'
Traceback (most recent call last):
  File "lib/doodleDelegate.pyc", line 89, in sendEvent_
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/vanilla/vanillaBase.py", line 520, in action_
  File "/Users/bman/Library/Application Support/RoboFont/plugins/GlyphConstruction.roboFontExt/lib/glyphConstructionController.py", line 805, in reload
  File "/Users/bman/Library/Application Support/RoboFont/plugins/GlyphConstruction.roboFontExt/lib/glyphConstructionController.py", line 647, in constructionsCallback
  File "/Users/bman/Library/Application Support/RoboFont/plugins/GlyphConstruction.roboFontExt/lib/glyphConstruction.py", line 1212, in GlyphConstructionBuilder
  File "/Users/bman/Library/Application Support/RoboFont/plugins/GlyphConstruction.roboFontExt/lib/glyphConstruction.py", line 200, in _set_leftMargin
TypeError: unsupported operand type(s) for -: 'str' and 'int'
```

**Comment by typemytype** [comment]
oh 🐔  or 🥚  story..

what should the outcome if this equation be: `glyphName-10` and what value should it be when there is a glyph with the name `glyphName-10` 

I will make the `"glyphName"-10` stronger and available inside a glyph attribute math.

thanks!!

**Comment by typemytype** [comment]
could you test this patch before I tag a new version number? 

thanks

**Comment by typoman** [comment]
Thank you for the patch. I tested the the following case:

```
>g2-tmp = ^ g1-tmp*2, g1-tmp*2
```

The resulting `g2-tmp` glyph now has zero width, but it should follow the `g1-tmp` margins which is not zero width. ლ(▀̿̿Ĺ̯̿̿▀̿ლ)

**Comment by typemytype** [comment]
in case you have glyph names containing -+* its advised to wrap it inbetween quotes

```
>g2-tmp = ^ "g1-tmp"*2, "g1-tmp"*2
```

**Comment by typoman** [comment]
Thank you, with the latest commit everything seems to work.
